version: 2.1
orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
  deploy-backend-ebs:
    docker:
      - image: cimg/node:15.9.0
    steps:
      - checkout
      - eb/setup
      - run:
          name: eb cli install
          command: |
            python .\aws-elastic-beanstalk-cli-setup\scripts\ebcli_installer.py
      - run:
          name: eb environment variables
          command: |
            cd udagram-api && eb setenv PORT=$PORT POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_DB=$POSTGRES_DB
workflows:
  node-build-tests:
    jobs:
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
      - run:
          name: Front-End test
          command: |
            npm run frontend:test
      - run:
          name: Back-End test
          command: |
            npm run backend:test
